permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
encoding: utf-8

# Setup
title:               Oleksii Oleksenko
description:         My blog...
url: https://oleksiioleksenko.github.io/
baseurl: ""
urlimg: https://oleksiioleksenko.github.io/images/
markdown: kramdown
kramdown:
  math_engine: mathjax

paginate: 5
paginate_path: "/blog/page:num"
excerpt_separator: <!--more-->
default_bg: sitebg.jpg
default_logo: sitelogo.png
safe: false
timezone:    Europe/Berlin
future:      true


## code highlight options
syntax_highlighter: rouge
input: GFM

gems:
  - github-pages
  - font-awesome-sass
  - jekyll-redirect-from
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "_plugins", "public/dormant"]

# About/contact
author:
  name:              Oleksii Oleksenko
  url:               https://twitter.com/oleksii_o
  avatar:         av.png
  #email:

# Owner/author information
owner:
  name:           Oleksii Oleksenko
  avatar:         av.png
  twitter:        oleksii_o
  github:         OleksiiOleksenko
  linkedin:       https://www.linkedin.com/in/oleksiioleksenko/
  gscholar: qHCADLcAAAAJ

## sidebar links:
# For external links add external: true
links:
  - title: <i class="iconside iconm-home"></i> Home
    url: /
  - title: <i class="iconside iconm-quill"></i> Blog
    url: /blog/
  - title: <i class="iconside iconm-envelop"></i> Contact
    url: /contact/
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml


# Add disqus username for Disqus comment board:
disqus_shortname: oleksiioleksenko-github-io

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-76459048-1


## END ##