- year: 2026
  text: "PC Member, USENIX Security"
- year: 2025
  text: "PC Member, USENIX Security"
- year: 2024
  text: "PC Member, CCS"
- year: 2023
  text: "PC Member, USENIX Security (Winter Cycle)"
- year: 2023
  text: "PC Member, CCS"
- year: 2022
  text: "PC Member, CCS"
- year: 2022
  text: "Artifact Evaluation Committee Member, EuroSys"
- year: 2021
  text: "Artifact Evaluation Committee Member, SOSP"
- year: 2019
  text: "Shadow PC Member, EuroSys"
- year: "2018-2019"
  text: "Sub-reviewer, EuroSys"
- year: "2017-2020"
  text: "Sub-reviewer, DSN"
